### ISSUE TITLE
Many-To-Many not editable - hasManyFormElemn raises error

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#19]
When creating the current latest ScienceDb-Instance using [ScienceDbStarterPack](https://github.com/ScienceDb/ScienceDbStarterPack) master branch, and starting it with
`docker-compose -f docker-compose-dev.yml up --force-recreate --remove-orphans` an error occurs when editing the user to roles association for the default user automatically created by the seeders (see [`REAME`](https://github.com/ScienceDb/ScienceDbStarterPack/blob/master/README.md) for more details)

See attached screenshot documenting what was tried in the edit user case.

The Browser console reports the following error:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'length' of null"

found in

---> <Autocomplete> at src/js/components/vue-autocomplete.vue
       <HasManyFormElement> at src/components/hasManyFormElemn.vue
         <UserFormElemns> at src/components/userFormElemns.vue
           <UserEditForm> at src/components/userEditForm.vue
             <App> at src/App.vue
               <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1862
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6911
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'length' of null
    at VueComponent.handleKeyDown (vue2-autocomplete.js?29ce:399)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLInputElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLInputElement.original._wrapper (vue.runtime.esm.js?2b0e:6911)
```

**Comment by asishallab** [comment]
![many-to-many-component-error](https://user-images.githubusercontent.com/575529/55401582-7ed34e00-5551-11e9-85b3-4eeec17bf446.png)

**Comment by vsuaste** [comment]
After reproducing the error a doing some debugin, I finally came up with what is causing this error.
The problem is that when doing the filter step, we are filtering by both, `label` and `sublabel`, taking both as text, but sequelize can not compare an integer(id) with comparator `like`, therefore throws an error. 
In this particular case we are using `id` field as `sublabel` in the model `user` and that throws the error by sequelize. 

We have two options now:
1.- Use as `label` and `sublabel` only string type fields.
2.- Cancel the filter by `sublabel` in which case only the `label` should be string type and `sublabel` can be any type.

**Comment by asishallab** [comment]
@vsuaste thanks for clarifying this issue. 
I'd suggest to go with your suggestion `1` - only use String types.
